package chess.engine.training;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Full self improvement loop:
 *
 * <p>1. Generate games using the current best network.
 * 2. Train on the accumulated game data.
 * 3. Keep the best validation network instead of blindly accepting the latest weights.
 * 4. Repeat.
 *
 * <p>The pipeline is deliberately conservative about iteration boundaries. GameTrainer is responsible
 * for validation, checkpointing, early stopping, and protecting nnue_weights_best.bin. The pipeline
 * therefore never replaces the best network merely because an iteration finished.
 *
 * <p>Usage:
 * {@code TrainingPipeline [iterations] [gamesPerIteration] [timePerMoveMs] [threads] [epochs]}
 */
public final class TrainingPipeline {

  private static final int DEFAULT_ITERATIONS = 10;
  private static final int DEFAULT_GAMES_PER_ITERATION = SelfPlayGenerator.DEFAULT_GAMES;
  private static final long DEFAULT_TIME_PER_MOVE_MS = SelfPlayGenerator.DEFAULT_TIME_PER_MOVE_MS;

  /*
   * Do not make this enormous. More epochs are useful only while validation continues to improve.
   * GameTrainer has its own early stopping, so this is an upper bound rather than a demand to run
   * every epoch.
   */
  private static final int DEFAULT_EPOCHS = 40;

  /*
   * Give the self play stage enough data to move the distribution, but keep iterations reasonably
   * frequent so the network gets fresh games from its latest best checkpoint.
   */
  private static final int MIN_GAMES_PER_ITERATION = 100;

  /*
   * If the trainer's output files exist, self play should use the best network selected by
   * GameTrainer. We never delete or overwrite that file from this class.
   */
  private static final String BEST_WEIGHTS_FILE = "nnue_weights_best.bin";
  private static final String WORKING_WEIGHTS_FILE = "nnue_weights.bin";

  public static void main(String[] args) {
    int iterations = args.length > 0 ? Integer.parseInt(args[0]) : DEFAULT_ITERATIONS;
    int gamesPerIteration =
            args.length > 1 ? Integer.parseInt(args[1]) : DEFAULT_GAMES_PER_ITERATION;
    long timePerMoveMs = args.length > 2 ? Long.parseLong(args[2]) : DEFAULT_TIME_PER_MOVE_MS;
    int threads =
            args.length > 3
                    ? Integer.parseInt(args[3])
                    : Math.max(1, Runtime.getRuntime().availableProcessors() / 2);
    int epochs = args.length > 4 ? Integer.parseInt(args[4]) : DEFAULT_EPOCHS;

    validateArguments(iterations, gamesPerIteration, timePerMoveMs, threads, epochs);

    /*
     * One seed is used as the root for the whole run, but every iteration gets a different
     * deterministic offset. This prevents accidentally replaying the exact same self play stream.
     */
    long baseSeed = System.nanoTime();

    printConfiguration(iterations, gamesPerIteration, timePerMoveMs, threads, epochs);

    double previousBestMse = readBestMseFromHistory();

    for (int iteration = 1; iteration <= iterations; iteration++) {
      System.out.println();
      System.out.println("========================================");
      System.out.println("ITERATION " + iteration + "/" + iterations);
      System.out.println("========================================");

      /*
       * IMPORTANT:
       * Self play happens BEFORE training, so the games are generated by the network produced by
       * the previous successful training stage. GameTrainer itself protects the all time best.
       */
      if (!ensureNetworkExists()) {
        System.err.println(
                "No existing network was found. Self play will use the project's normal initialization.");
      } else {
        System.out.println("Self play source:");
        System.out.println("  best checkpoint   : " + BEST_WEIGHTS_FILE);
        System.out.println("  working checkpoint: " + WORKING_WEIGHTS_FILE);
      }

      try {
        SelfPlayGenerator generator =
                new SelfPlayGenerator(
                        gamesPerIteration,
                        timePerMoveMs,
                        mixSeed(baseSeed, iteration),
                        threads);

        long generationStart = System.nanoTime();
        generator.generate();
        long generationSeconds = (System.nanoTime() - generationStart) / 1_000_000_000L;

        System.out.println(
                "Self play iteration "
                        + iteration
                        + " complete in "
                        + generationSeconds
                        + "s.");
      } catch (IOException e) {
        System.err.println("Generation failed, stopping pipeline: " + e.getMessage());
        e.printStackTrace(System.err);
        System.exit(1);
      } catch (RuntimeException e) {
        System.err.println("Generation failed, stopping pipeline: " + e.getMessage());
        e.printStackTrace(System.err);
        System.exit(1);
      }

      /*
       * Train only after the complete self play batch exists. GameTrainer decides which checkpoint
       * is actually better using the fixed validation set.
       */
      try {
        long trainingStart = System.nanoTime();

        new GameTrainer(epochs).run();

        long trainingSeconds = (System.nanoTime() - trainingStart) / 1_000_000_000L;

        System.out.println(
                "Training iteration "
                        + iteration
                        + " complete in "
                        + trainingSeconds
                        + "s.");
      } catch (IOException e) {
        System.err.println("Training failed, stopping pipeline: " + e.getMessage());
        e.printStackTrace(System.err);
        System.exit(1);
      } catch (RuntimeException e) {
        System.err.println("Training failed, stopping pipeline: " + e.getMessage());
        e.printStackTrace(System.err);
        System.exit(1);
      }

      /*
       * Do not treat "training completed" as "the network improved". GameTrainer's all time best
       * checkpoint is the authority. This informational check makes the iteration boundary obvious
       * in long overnight runs.
       */
      double currentBestMse = readBestMseFromHistory();

      if (Double.isFinite(currentBestMse)) {
        if (!Double.isFinite(previousBestMse)) {
          System.out.printf(
                  "Iteration %d produced first tracked validation result: %.4f%n",
                  iteration, currentBestMse);
        } else if (currentBestMse < previousBestMse - 1.0e-9) {
          System.out.printf(
                  "Iteration %d improved all time validation MSE: %.4f -> %.4f%n",
                  iteration, previousBestMse, currentBestMse);
        } else {
          System.out.printf(
                  "Iteration %d did not improve all time validation MSE: %.4f -> %.4f%n",
                  iteration, previousBestMse, currentBestMse);
        }

        previousBestMse = Math.min(previousBestMse, currentBestMse);
      }

      /*
       * Explicitly verify that the protected checkpoint still exists. Never copy the working file
       * over it here: GameTrainer already implements the "only replace on validation improvement"
       * rule.
       */
      if (Files.isRegularFile(Paths.get(BEST_WEIGHTS_FILE))) {
        System.out.println("Protected best checkpoint is present: " + BEST_WEIGHTS_FILE);
      } else {
        System.err.println(
                "WARNING: "
                        + BEST_WEIGHTS_FILE
                        + " does not exist after training. Check GameTrainer checkpointing.");
      }

      System.out.println("Iteration " + iteration + " finished.");
    }

    System.out.println();
    System.out.println("========================================");
    System.out.println("PIPELINE COMPLETE");
    System.out.println("========================================");
    System.out.println("Best checkpoint : " + BEST_WEIGHTS_FILE);
    System.out.println("Working weights : " + WORKING_WEIGHTS_FILE);

    double finalBest = readBestMseFromHistory();
    if (Double.isFinite(finalBest)) {
      System.out.printf("Best recorded validation MSE: %.4f%n", finalBest);
    }

    System.out.println(
            "The engine should load the protected best checkpoint first, as configured by GameTrainer.");
  }

  private static void validateArguments(
          int iterations,
          int gamesPerIteration,
          long timePerMoveMs,
          int threads,
          int epochs) {

    if (iterations <= 0) {
      throw new IllegalArgumentException("iterations must be > 0");
    }

    if (gamesPerIteration < MIN_GAMES_PER_ITERATION) {
      throw new IllegalArgumentException(
              "gamesPerIteration must be at least " + MIN_GAMES_PER_ITERATION);
    }

    if (timePerMoveMs <= 0) {
      throw new IllegalArgumentException("timePerMoveMs must be > 0");
    }

    if (threads <= 0) {
      throw new IllegalArgumentException("threads must be > 0");
    }

    if (epochs <= 0) {
      throw new IllegalArgumentException("epochs must be > 0");
    }
  }

  private static void printConfiguration(
          int iterations,
          int gamesPerIteration,
          long timePerMoveMs,
          int threads,
          int epochs) {

    System.out.println();
    System.out.println("============= TRAINING PIPELINE =============");
    System.out.println("Iterations              : " + iterations);
    System.out.println("Games / iteration       : " + gamesPerIteration);
    System.out.println("Time / move             : " + timePerMoveMs + " ms");
    System.out.println("Training threads        : " + threads);
    System.out.println("Maximum epochs          : " + epochs);
    System.out.println("Protected best network  : " + BEST_WEIGHTS_FILE);
    System.out.println("Working network         : " + WORKING_WEIGHTS_FILE);
    System.out.println("==============================================");
  }

  /**
   * Produces a different seed for every iteration while avoiding the trivial
   * {@code baseSeed + iteration} sequence.
   */
  private static long mixSeed(long baseSeed, int iteration) {
    long z = baseSeed + 0x9E3779B97F4A7C15L * iteration;
    z = (z ^ (z >>> 30)) * 0xBF58476D1CE4E5B9L;
    z = (z ^ (z >>> 27)) * 0x94D049BB133111EBL;
    return z ^ (z >>> 31);
  }

  /**
   * Checks whether there is already a trained checkpoint.
   *
   * <p>We check the protected best first because that is the model GameTrainer considers strongest.
   */
  private static boolean ensureNetworkExists() {
    return Files.isRegularFile(Path.of(BEST_WEIGHTS_FILE))
            || Files.isRegularFile(Path.of(WORKING_WEIGHTS_FILE));
  }

  /**
   * Reads the newest all time best MSE from the existing training history.
   *
   * <p>This is informational only. GameTrainer remains the source of truth for model selection.
   * If the history is absent or has an unexpected format, the pipeline simply reports no value.
   */
  private static double readBestMseFromHistory() {
    Path history = Path.of("training_history.log");

    if (!Files.isRegularFile(history)) {
      return Double.NaN;
    }

    double best = Double.POSITIVE_INFINITY;

    try {
      for (String line : Files.readAllLines(history)) {
        int marker = line.indexOf("NEW BEST");
        if (marker < 0) {
          continue;
        }

        int mseMarker = line.indexOf("valMse ", marker);
        if (mseMarker < 0) {
          continue;
        }

        int start = mseMarker + "valMse ".length();
        int end = start;

        while (end < line.length()) {
          char c = line.charAt(end);
          if (!(Character.isDigit(c) || c == '.' || c == 'e' || c == 'E' || c == '-'
                  || c == '+')) {
            break;
          }
          end++;
        }

        if (end > start) {
          try {
            double value = Double.parseDouble(line.substring(start, end));
            if (Double.isFinite(value)) {
              best = Math.min(best, value);
            }
          } catch (NumberFormatException ignored) {
            // Ignore malformed history entries.
          }
        }
      }
    } catch (IOException e) {
      System.err.println("Could not read training history: " + e.getMessage());
      return Double.NaN;
    }

    return Double.isFinite(best) ? best : Double.NaN;
  }

  private TrainingPipeline() {}
}